ExpenseTracker/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace ExpenseTracker.Controllers
{
    [Authorize]
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/AddOrEdit
        public IActionResult AddOrEdit(int id=0)
        {
            if (id == 0) { return View(new Category()); }
            else
            { return View(_context.Categories.Find(id)); }
        }

        // POST: Categories/AddOrEdit
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("CategoryId,Title,Icon,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                if(category.CategoryId==0) { _context.Add(category); }
                else
                    _context.Update(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

       


       

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        
    }
}

ExpenseTracker/Controllers/DashboardController.cs
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;

namespace ExpenseTracker.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ApplicationDbContext _context;
        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<ActionResult> Index()
        {
            DateTime StartDate = DateTime.Today.AddDays(-6);
            DateTime EndDate = DateTime.Today;
            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();

            //Total Income
            int TotalIncome = SelectedTransactions
                .Where(i => i.Category.Type == "Income")
                .Sum(j => j.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C0");

            //Total Expense
            int TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C0");

            //Balance
            int Balance = TotalIncome - TotalExpense;
            CultureInfo culture = CultureInfo.CreateSpecificCulture("en-US");
            culture.NumberFormat.CurrencyNegativePattern = 1;
            ViewBag.Balance = String.Format(culture, "{0:C0}", Balance);

            //Doughnut Chart - Expense By Category
            ViewBag.DoughnutChartData = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .GroupBy(j => j.Category.CategoryId)
                .Select(k => new
                {
                    categoryTitleWithIcon = k.First().Category.Icon + " " + k.First().Category.Title,
                    amount = k.Sum(j => j.Amount),
                    formattedAmount = k.Sum(j => j.Amount).ToString("C0"),
                })
                .OrderByDescending(l => l.amount)
                .ToList();



            //Spline Chart - Income vs Expense

            //Income
            List<SplineChartData> IncomeSummary = SelectedTransactions
                .Where(i => i.Category.Type == "Income")
                .GroupBy(j => j.Date)
                .Select(k => new SplineChartData()
                {
                    day = k.First().Date.ToString("dd-MMM"),
                    income = k.Sum(l => l.Amount)
                })
                .ToList();

            //Expense
            List<SplineChartData> ExpenseSummary = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .GroupBy(j => j.Date)
                .Select(k => new SplineChartData()
                {
                    day = k.First().Date.ToString("dd-MMM"),
                    expense = k.Sum(l => l.Amount)
                })
                .ToList();

            //Combine Income & Expense
            string[] Last7Days = Enumerable.Range(0, 7)
                .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
                .ToArray();

            ViewBag.SplineChartData = from day in Last7Days
                                      join income in IncomeSummary on day equals income.day into dayIncomeJoined
                                      from income in dayIncomeJoined.DefaultIfEmpty()
                                      join expense in ExpenseSummary on day equals expense.day into expenseJoined
                                      from expense in expenseJoined.DefaultIfEmpty()
                                      select new
                                      {
                                          day = day,
                                          income = income == null ? 0 : income.income,
                                          expense = expense == null ? 0 : expense.expense,
                                      };

            ViewBag.RecentTransactions = await _context.Transactions
                .Include(i => i.Category)
                .OrderByDescending(j => j.Date)
                .Take(5)
                .ToListAsync();


            return View();
        }
    }

    public class SplineChartData
    {
        public string day;
        public int income;
        public int expense;

    }
}

ExpenseTracker/Controllers/LoginRegistersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpenseTracker.Models;
using Microsoft.AspNetCore.Authorization;

namespace ExpenseTracker.Controllers
{
    [Authorize]
    public class LoginRegistersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LoginRegistersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: LoginRegisters
        public async Task<IActionResult> Index()
        {
              return _context.LoginRegisters != null ? 
                          View(await _context.LoginRegisters.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.LoginRegisters'  is null.");
        }

        // GET: LoginRegisters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.LoginRegisters == null)
            {
                return NotFound();
            }

            var loginRegister = await _context.LoginRegisters
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loginRegister == null)
            {
                return NotFound();
            }

            return View(loginRegister);
        }

        // GET: LoginRegisters/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: LoginRegisters/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FirstName,LastName,Email,Phone")] LoginRegister loginRegister)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loginRegister);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(loginRegister);
        }

        // GET: LoginRegisters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.LoginRegisters == null)
            {
                return NotFound();
            }

            var loginRegister = await _context.LoginRegisters.FindAsync(id);
            if (loginRegister == null)
            {
                return NotFound();
            }
            return View(loginRegister);
        }

        // POST: LoginRegisters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FirstName,LastName,Email,Phone")] LoginRegister loginRegister)
        {
            if (id != loginRegister.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loginRegister);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoginRegisterExists(loginRegister.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loginRegister);
        }

        // GET: LoginRegisters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.LoginRegisters == null)
            {
                return NotFound();
            }

            var loginRegister = await _context.LoginRegisters
                .FirstOrDefaultAsync(m => m.Id == id);
            if (loginRegister == null)
            {
                return NotFound();
            }

            return View(loginRegister);
        }

        // POST: LoginRegisters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.LoginRegisters == null)
            {
                return Problem("Entity set 'ApplicationDbContext.LoginRegisters'  is null.");
            }
            var loginRegister = await _context.LoginRegisters.FindAsync(id);
            if (loginRegister != null)
            {
                _context.LoginRegisters.Remove(loginRegister);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LoginRegisterExists(int id)
        {
          return (_context.LoginRegisters?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ExpenseTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Expense Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
   
    <link href="https://cdn.syncfusion.com/ej2/20.1.55/bootstrap5-dark.css" rel="stylesheet" />
    
    <link href="https://fonts.googleapis.com/css2?family=Hedvig+Letters+Sans&family=Inter:wght@300;400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseTracker.styles.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/23.2.4/dist/ej2.min.js"></script>
</head>
<style>
    .container-fluid .nav-link{
        text-decoration: none !important;
        color: #000;
    }
</style>
<body class="e-bigger">
    
    @*
    <partial name="_SideBar" />
    *@
   
    <header>

    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3 ">
    <div class="container-fluid">


    <a class="nav-link " asp-area="" asp-controller="Dashboard" asp-action="Index"><i class="fa-solid fa-list"></i></a>

    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">  Expense Tracker</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">

@*
                        <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="LoginRegisters" asp-action="Index">User</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
*@
    

    </ul>
    </div>
    </div>
    <partial name="_LoginPartial"/>
    </nav>
    </header>
   
   
    @**@
    <div class="main-content">
      <div class="container mt-3">
        <div class="row justify-content-center">
                <div class="@(ViewData["isDashboard"] == null?"col-md-7":"col-md-12")">
                <main role="main" class="pb-3">
                        @if (ViewData["isDashboard"] == null)
                        {
                            <div class="row">
                                <div class="col-md-5">
                                    <div class="d-flex flex-cloumn mb-3">
                                        <div class="d-flex mb-1">
                                            <div class="flex-grow-1 ">
                                                <h3 class="fw-bold">@ViewData["PageTitle"]</h3>
                                            </div>
                                            <div>
                                                @if (ViewData["PageActionText"] != null)
                                                {
                                                    <a class="btn btn-success" href="@ViewData["PageActionUrl"]">
                                                        @ViewData["PageActionText"]
                                                    </a>
                                                }
                                            </div>
                                        </div>
                                    </div>
                                    <div class="d-flex mb-1">
                                        <ejs-breadcrumb id="breadcrumb"
                                                separatorTemplate="@Html.Raw("<span class='fa-solid fa-angle-right'></span>")">

                                        </ejs-breadcrumb>
                                    </div>

                                </div>
                            </div>
                        }
                        @RenderBody()
                </main>
            </div>
        </div>
       </div>
    </div>

    @*
    <footer class="border-top footer text-muted">
    <div class="container ">
    &copy; 2023 - ExpenseTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>
    *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
   
</body>
</html>

ExpenseTracker/Views/Shared/_SideBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@


@{
    List<Object> menuItems = new List<Object>();
    menuItems.Add(new
    {
        text = "Profile",
        separator = true,

    });
    menuItems.Add(new
    {
        text = "User",
        url = "/LoginRegisters",
        iconCss = "fa-solid fa-user"
        
    });
    menuItems.Add(new
    {
        text = "Options",
        separator = true,

    });
    menuItems.Add(new
    {
        text = "Dashboard",
        url = "/Dashboard",
        iconCss = "fa-solid fa-box"
    });
    menuItems.Add(new
    {
        text = "Categories",
        url = "/Categories",
        iconCss="fa-solid fa-folder-closed"
    });
    menuItems.Add(new
    {
        text = "Transactions",
        url = "/Transaction",
        iconCss="fa-solid fa-arrow-right-arrow-left"
    });
    menuItems.Add(new
    {
        text = "Settings",
        url = "/Identity/Account/Manage",
        iconCss = "fa-solid fa-gear"

    });
}

<ejs-sidebar id="sidebar" width="290px" style="margin-top: 120px;" enableDock dockSize="120px">
    <e-content-template >
        
        <ejs-menu id="menu" items="menuItems" orientation="Vertical" hamburgerMode ></ejs-menu>
    </e-content-template>
</ejs-sidebar>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        dockBar = document.getElementById('sidebar').ej2_instances[0];
        document.getElementById('sidebar-toggler').onclick = function () {
            dockBar.toggle();
        };
    });

</script>